namespace Mesawer.ApplicationLayer.Enums;

public enum PhoneNumberCode
{
    Afghanistan                 = 93_9,
    Albania                     = 355_9, // Uncertain
    Algeria                     = 213_9,
    AmericanSamoa               = 684_10, // Uncertain
    Andorra                     = 376_9,  // Uncertain
    Angola                      = 244_9,  // Uncertain
    Anguilla                    = 264_10, // Uncertain
    AntiguaAndBarbuda           = 268_10, // Uncertain
    Argentina                   = 54_9,   // Uncertain
    Armenia                     = 374_6,
    Aruba                       = 297_7,
    Ascension                   = 247_9, // Uncertain
    Australia                   = 61_9,
    Austria                     = 43_10,
    Azerbaijan                  = 994_9,
    Bahamas                     = 242_10, // Uncertain
    Bahrain                     = 973_8,
    Bangladesh                  = 880_10,
    Barbados                    = 246_10, // Uncertain
    Belarus                     = 375_9,
    Belgium                     = 32_9,
    Belize                      = 501_7,
    Benin                       = 229_6, // Uncertain
    Bermuda                     = 441_10,
    Bhutan                      = 975_9, // Uncertain
    Bolivia                     = 591_9, // Uncertain
    Bonaire                     = 599_9, // Uncertain,
    SintEustatiusAndSaba        = 599_9, // Uncertain
    BosniaAndHerzegovina        = 387_8, // Uncertain
    Botswana                    = 267_9, // Uncertain
    Brazil                      = 55_11,
    BritishIndianOceanTerritory = 246_7,  // Uncertain
    BritishVirginIslands        = 284_10, // Uncertain
    Brunei                      = 673_9,  // Uncertain
    Bulgaria                    = 359_9,
    BurkinaFaso                 = 226_8,
    Burundi                     = 257_9, //Uncertain
    Cambodia                    = 855_9,
    Cameroon                    = 237_9,
    Canada                      = 1_10,
    CentralAfricanRepublic      = 236_9, //Uncertain
    Chad                        = 235_8,
    Chile                       = 56_9,
    China                       = 86_11,
    Colombia                    = 57_10,
    Comoros                     = 269_9, //Uncertain
    CookIslands                 = 682_5,
    CostaRica                   = 506_8,
    Croatia                     = 385_9,
    Cuba                        = 53_9,  //Uncertain
    Curaçao                     = 599_9, //Uncertain
    Cyprus                      = 357_8,
    CzechRepublic               = 420_9,
    Denmark                     = 45_8,
    Djibouti                    = 253_9, //Uncertain
    Ecuador                     = 593_9,
    Egypt                       = 20_10,
    England                     = 44_10,
    Eritrea                     = 291_9, //Uncertain
    Estonia                     = 372_9, //Uncertain
    Eswatini                    = 268_8,
    Ethiopia                    = 251_9, //Uncertain
    FalklandIslands             = 500_5,
    FaroeIslands                = 298_5,
    Fiji                        = 679_9, //Uncertain
    Finland                     = 358_10,
    France                      = 33_9,
    Gabon                       = 241_7,
    Gambia                      = 220_9, //Uncertain
    Georgia                     = 995_9,
    Germany                     = 49_10,
    Ghana                       = 233_9,
    Gibraltar                   = 350_9, //Uncertain
    Greece                      = 30_10,
    Greenland                   = 299_6,
    Grenada                     = 473_10,
    Guadeloupe                  = 590_9,
    Guam                        = 671_10,
    Guatemala                   = 502_8,
    Guyana                      = 592_9, //Uncertain
    Haiti                       = 509_9, //Uncertain
    Honduras                    = 504_8,
    HongKong                    = 852_8,
    Hungary                     = 36_9,
    Iceland                     = 354_9, //Uncertain
    India                       = 91_10,
    Indonesia                   = 62_9,
    Iraq                        = 964_10,
    Iran                        = 98_9, //Uncertain
    Ireland                     = 353_9,
    Israel                      = 972_9,
    Italy                       = 39_44452,
    Jamaica                     = 658_10,
    Japan                       = 81_10,
    Jordan                      = 962_9,
    Kazakhstan                  = 7_10,
    Kenya                       = 254_10,
    Kiribati                    = 686_8,
    Kosovo                      = 383_8,
    Kuwait                      = 965_8,
    Kyrgyzstan                  = 996_9, //Uncertain
    Laos                        = 856_9, //Uncertain
    Latvia                      = 371_8,
    Lebanon                     = 961_7,
    Lesotho                     = 266_9, //Uncertain
    Liberia                     = 231_7,
    Libya                       = 218_10,
    Liechtenstein               = 423_9, //Uncertain
    Lithuania                   = 370_8,
    Luxembourg                  = 352_9,
    Macau                       = 853_9, //Uncertain
    Madagascar                  = 261_9, //Uncertain
    Malawi                      = 265_9, //Uncertain
    Malaysia                    = 60_7,
    Maldives                    = 960_7,
    Mali                        = 223_8,
    Malta                       = 356_8,
    MarshallIslands             = 692_7,
    Martinique                  = 596_9,
    Mauritania                  = 222_9, //Uncertain
    Mauritius                   = 230_8,
    Mayotte                     = 262_9, //Uncertain
    Mexico                      = 52_10,
    Moldova                     = 373_8,
    Monaco                      = 377_9, //Uncertain
    Mongolia                    = 976_8,
    Montenegro                  = 382_8,
    Montserrat                  = 664_10,
    Morocco                     = 212_9, //Uncertain
    Mozambique                  = 258_12,
    Myanmar                     = 95_8,
    Namibia                     = 264_9, //Uncertain
    Nauru                       = 674_9, //Uncertain
    Netherlands                 = 31_9,
    Nepal                       = 977_10,
    NewCaledonia                = 687_6,
    NewZealand                  = 64_8,
    Nicaragua                   = 505_8,
    Niger                       = 227_8,
    Nigeria                     = 234_8,
    Niue                        = 683_4,
    Norway                      = 47_8,
    Oman                        = 968_8,
    Pakistan                    = 92_10,
    Palau                       = 680_7,
    Palestine                   = 970_9,
    Panama                      = 507_8,
    Paraguay                    = 595_9,
    Peru                        = 51_9,
    Philippines                 = 63_10,
    Poland                      = 48_9,
    Portugal                    = 351_9,
    Qatar                       = 974_8,
    Reunion                     = 262_9,
    Romania                     = 40_10,
    Russia                      = 7_10,
    Rwanda                      = 250_9, //Uncertain
    Samoa                       = 685_5,
    SaoTomeAndPrincipe          = 239_9, //Uncertain
    SaudiArabia                 = 966_10,
    Senegal                     = 221_9, //Uncertain
    Serbia                      = 381_8,
    Seychelles                  = 248_9, //Uncertain
    SierraLeone                 = 232_9, //Uncertain
    SintMaarten                 = 721_10,
    Singapore                   = 65_8,
    Slovakia                    = 421_9,
    Slovenia                    = 386_9, //Uncertain
    SolomonIslands              = 677_7,
    Somalia                     = 252_7,
    SouthAfrica                 = 27_9,
    SouthKorea                  = 82_9,
    SouthSudan                  = 211_9, //Uncertain
    Spain                       = 34_9,
    SriLanka                    = 94_7,
    Sudan                       = 249_9, //Uncertain
    Suriname                    = 597_9, //Uncertain
    Sweden                      = 46_7,  //Uncertain
    Switzerland                 = 41_9,
    Syria                       = 963_9,
    Taiwan                      = 886_9,
    Tajikistan                  = 992_9, //Uncertain
    Tanzania                    = 255_9, //Uncertain
    Thailand                    = 66_9,
    TimorLeste                  = 670_9, //Uncertain
    Togo                        = 228_8,
    Tokelau                     = 690_9, //Uncertain
    Tonga                       = 676_9, //Uncertain
    TrinidadAndTobago           = 868_10,
    Tunisia                     = 216_8,
    Turkey                      = 90_11,
    Turkmenistan                = 993_9, //Uncertain
    TurksAndaicosIslands        = 649_10,
    Tuvalu                      = 688_9, //Uncertain
    Uganda                      = 256_9, //Uncertain
    Ukraine                     = 380_9,
    UnitedArabEmirates          = 971_9,
    UnitedKingdom               = 44_10,
    UnitedStates                = 1_10,
    Uruguay                     = 598_9, //Uncertain
    Uzbekistan                  = 998_9, //Uncertain
    Vanuatu                     = 678_9, //Uncertain
    Venezuela                   = 58_7,
    Vietnam                     = 84_9,
    VirginIslands               = 340_10,
    WallisAndFutuna             = 681_9, //Uncertain
    WestBank                    = 970_9, //Uncertain
    Yemen                       = 967_9,
    Zambia                      = 260_9, //Uncertain
    Zimbabwe                    = 263_9
}
